### ISSUE TITLE
Sharing extension isn‘t there if web page is a PDF

### ISSUE THREAD

**Issue by maiksd** [certificate-helper/TLS-Inspector#105] opened 2018-03-31 19:34 UTC
**Affected Version:**
1.7.0 (40)

**Is this a Test Flight version or the App Store version?**
App Store

**Device and iOS Version:**
iPad Pro 10,5“ running iOS 11.3

**What steps will reproduce the problem?**

1. Visit https://www.axis.com/files/manuals/um_M1004w_63351_en_1603.pdf
2. Try to bring up the sharing extension

**What is the expected output?**
Sharing extension is visible and can display the certificate details

**What do you see instead?**
Sharing extension not included in the list of possible extensions to call

**Please provide any additional information below.**

**Comment by ecnepsnai** [comment] 2018-03-31 23:02
Duplicate of #75. When viewing a document in Safari (such as a picture, audio file, or image) the share sheet is for the document itself, not the URL for it, and adding support for TLS Inspector would make already confusing code even worse.

**Closed by ecnepsnai** 2018-03-31 23:02 UTC
