### ISSUE TITLE
Certificates Issued by manually trusted CA are marked as "Untrusted"

### ISSUE THREAD

**Issue by logopk** [certificate-helper/TLS-Inspector#82] opened 2017-11-13 21:11 UTC
**Affected Version:**
1.60 (31)

**Is this a Test Flight version or the App Store version?**
AppStore

**Device and iOS Version:**
iPhone 6s, iOS 11.1.1

**What steps will reproduce the problem?**

1. self signed local domain
2. CA and cert in iPhones local profiles
3. TLS Inspector will mark certificate as „error“

**What is the expected output?**
Well as I accepted the CA in the installed profile, the domain should be green.

**What do you see instead?**
Certificates and Server marked as error (red x). There is no further info on what is wrong. Details would be helpful (also in case of non-selfsigned CAs/domains)

**Please provide any additional information below.**

**Comment by ecnepsnai** [comment] 2017-11-13 22:06
Hi @logopk 

Is this a managed device through a MDM? As far as I know, Apple removed the ability to mark a certificate as trusted using a profile on non-managed devices.

When you visit a website in Safari using an untrusted certificate, it does not mark that certificate as trusted for the system, only for Safari.

**Comment by logopk** [comment] 2017-11-13 22:29
It’s not managed by an MDM.
In the profile settings the CA is shown with a green „verified“

Would it be possible to show the cert details - not only „error“?

**Comment by ecnepsnai** [comment] 2017-11-13 22:33
When a profile says "Verified" it means that the only profile itself was signed by a trusted CA. It does not apply to any certificates that the profile may be installing.

I don't understand what you mean by "Show cert details" - TLS Inspector allows you to view certificate information for an untrusted certificate. As for showing more detailed information as to why the certificate is not trusted, that's already been requested here: https://github.com/certificate-helper/TLS-Inspector/issues/71

**Comment by logopk** [comment] 2017-11-14 07:33
My bad!

I hit the default port with client auth!

When I use the unprotected port I get a good result - still says „untrusted chain“ though.
The message in the info-popup says „untrusted chain the server certificate ... not trusted by the system because the server certificate is incorrect“?
Does this relate to the profiles that are only trusted by Safari, as you mentioned earlier?

**Comment by ecnepsnai** [comment] 2017-11-14 16:45
It looks like the error message for untrusted certificates is incorrect by saying "certificate is incorrect". This bug will track the change to fix that description.

**Comment by Shan11812** [comment] 2017-11-17 13:56
```
Is this a managed device through a MDM? As far as I know, Apple removed the ability to mark a certificate as trusted using a profile on non-managed devices.
```
Does this apply to CA that are manually installed too? I couldn't find any documentation saying so.

**Comment by ecnepsnai** [comment] 2017-11-19 17:21
Hey @Shan11812, you're correct CAs can still be installed after the iOS 10 changes, and upon investigation certs signed by manually trusted CAs are marked as untrusted. Hopefully I can identify something that marks these certificates as trusted, otherwise I'll have to open a bug with Apple.

**Comment by RowanKaag** [comment] 2018-03-11 13:04
I’m seeing the same results on my local (home) websites that have certificates which are signed by a non-public-CA-verified self-generated CA.

iOS’s Safari (as well as Chrome, Safari and Firefox on desktop) shows a padlock without any certificate warnings, and I have not overridden any trust verdicts beforehand other than manually trusting my self-generated CA certificate.

TLS Inspector however shows ‘Untrusted Chain’ when inspecting the certificate from within Safari’s extension. The same goes when manually entering the FQDN within the TLS Inspector app itself.

**Comment by ecnepsnai** [comment] 2018-03-11 17:30
@RowanKaag thank you, I am still working on this issue but as of right now there has been no progress. This appears to be a bug with the security framework in iOS. I plan to (just haven't gotten around to yet) opening a bug with Apple to discuss this problem.

**Comment by ecnepsnai** [comment] 2018-03-12 03:44
Found a working solution (and I feel like an idiot for not seeing it before). Merged and included in current beta. Tested locally.

**Comment by RowanKaag** [comment] 2018-03-12 07:17
I can confirm that with 1.7.0 (39) locally trusted (root) certificates are working. Sweet!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Closed** 2018-03-14 03:10 UTC
Labels: CertificateKit, bug, medium priority, merged

**Comment by Bethannfrum** [comment] 2018-04-26 06:14
Fix and restore to original form and release old documents
